# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kJaHSZMRu_oSTASVepXRv26ZbadEKPIL
"""

FACTORIAL

def fact(n):
  if n==0:
   return 1
  return n * fact(n-1)

n= int(input())
fact(n)